// Upbit API: Maket list
export const GET_MARKET_REQUEST = "GET_MARKET_REQUEST";
export const GET_MARKET_SUCCESS = "GET_MARKET_SUCCESS";
export const GET_MARKET_FAILURE = "GET_MARKET_FAILURE";

// Upbit API: Reltime Data
export const GET_REAL_TIME_DATA_REQUEST = "GET_REAT_TIME_DATA_REQUEST";
export const GET_REAL_TIME_DATA_SUCCESS = "GET_REAT_TIME_DATA_SUCCESS";
export const GET_REAL_TIME_DATA_FAILURE = "GET_REAT_TIME_DATA_FAILURE";

export const GET_REALTIME_DATA = "GET_REALTIME_DATA";
export const GET_REALTIME_DATA_SUCCESS = "GET_REALTIME_DATA_SUCCESS";
export const GET_REALTIME_DATA_ERROR = "GET_REALTIME_DATA_ERROR";

export const GET_MARKETCAP_REQUEST = "GET_MARKETCAP_REQUEST";
export const GET_MARKETCAP_SUCCESS = "GET_MARKETCAP_SUCCESS";
export const GET_MARKETCAP_FAILURE = "GET_MARKETCAP_FAILURE";

// FCAS score API
export const GET_SCORE_REQUEST = "GET_SCORE_REQUEST";
export const GET_SCORE_SUCCESS = "GET_SCORE_SUCCESS";
export const GET_SCORE_FAILURE = "GET_SCORE_FAILURE";

// Market Cap API
export const GET_MARKET_CAP_REQUEST = "GET_MARKET_CAP_REQUEST";
export const GET_MARKET_CAP_SUCCESS = "GET_MARKET_CAP_SUCCESS";
export const GET_MARKET_CAP_FAILURE = "GET_MARKET_CAP_FAILURE";

//Binance Data API
export const GET_BINANCE_REQUEST = "GET_BINANCE_REQUEST";
export const GET_BINANCE_SUCCESS = "GET_BINANCE_SUCCESS";
export const GET_BINANCE_FAILURE = "GET_BINANCE_FAILURE";

//CoinMarketCap API
export const GET_COIN_MARKET_CAP_REQUEST = "GET_COIN_MARKET_CAP_REQUEST";
export const GET_COIN_MARKET_CAP_SUCCESS = "GET_COIN_MARKET_CAP_SUCCESS";
export const GET_COIN_MARKET_CAP_FAILURE = "GET_COIN_MARKET_CAP_FAILURE";
